vich_uploader:
    db_driver: orm # or mongodb or phpcr

    metadata:
      type: attribute

    mappings:
      documents:
        uri_prefix: /admin_view_file
        upload_destination: '%uploaded_files_dir%'
        namer: App\Services\UploadedFileNamer