clear_env=off
zend_extension=xdebug

xdebug.mode=off
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

xdebug.idekey=PHPSTORM
xdebug.log=/tmp/xdebug.log

# xdebug 2.*
#xdebug.remote_enable=ON
#xdebug.remote_host=host.docker.internal
#xdebug.remote_port=9003
#xdebug.remote_log=/var/log/xdebug.log
#xdebug.remote_log_level=7