controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        type:     php
        prefix:   /_error